name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: boost
      run: sudo apt-get install cmake g++ libcurl4-gnutls-dev libfreetype6-dev libgif-dev libgtest-dev libjpeg-dev libpixman-1-dev libpng-dev libsdl2-dev libsdl2-image-dev libtinyxml2-dev libwebp-dev libx11-dev libxcursor-dev ninja-build libnode-dev zlib1g-dev libarchive-dev libfuse2
    - name: git
      run: git submodule update --init --recursive
    - name: mkdir
      run: mkdir build
    - name: cmake
      run: cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. && ninja libresprite
    - name: appimage
      run: |
        cd build/bin
        export ARCH="aarch64"
        sh ../../package_linux.sh
        mv ./LibreSprite-anylinux-$ARCH.AppImage ../../
    - name: Archive production artifacts
      if: runner.arch == 'aarch64'
      uses: actions/upload-artifact@v4
      with:
        name: libresprite-development-linux-arm64
        path: LibreSprite-anylinux-arm64.AppImage
        if-no-files-found: error
